baseURL = "http://zebbra.netlify.com/"
languageCode = "de"
title = "zebbra"
theme = "zebbra"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
googleAnalytics = "UA-44045593-1"
enableRobotsTXT = true

[params]
  copyright = "zebbra AG"
  description = "Wir sind zebbra, eine kreative Crew von agilen Denkern und Machern mit Ideen und innovativen Projekten"

[[menu.main]]
  name = "About"
  weight = -40
  url = "/#about"

[[menu.main]]
  name = "Services"
  weight = -30
  url = "/#services"

[[menu.main]]
  name = "Team"
  weight = -20
  url = "/#team"

[[menu.main]]
  name = "Customers"
  weight = -15
  url = "/#customers"

[[menu.main]]
  name = "Contact"
  weight = -10
  url = "/#contact"

[[menu.social]]
  name = "Facebook"
  pre = "<i class='fa fa-lg fa-fw fa-facebook-square'></i>"
  weight = 0
  url = "https://www.facebook.com/zebbra.ch"

[[menu.social]]
  name = "XING"
  pre = "<i class='fa fa-lg fa-fw fa-xing-square'></i>"
  weight = 0
  url = "https://www.xing.com/companies/zebbraag"
