# baseURL = "http://zebbra.netlify.com/"
disableAliases = true
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "de"
title = "zebbra"

[params]
title = "zebbra"
copyright = "zebbra AG"
description = "Wir sind zebbra, eine kreative Crew von agilen Denkern und Machern mit Ideen und innovativen Projekten."
images = ["/img/splash.png"]

[outputs]
home = ["HTML", "REDIRECTS", "HEADERS"]

[mediaTypes]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

[outputFormats.REDIRECTS]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

# Additional main menu items
[[menu.main]]
name = "About"
url = "/#about"
weight = -40

[[menu.main]]
name = "Services"
url = "/#services"
weight = -30

[[menu.main]]
name = "Team"
url = "/#team"
weight = -20

[[menu.main]]
name = "Customers"
url = "/#customers"
weight = -15

[[menu.main]]
name = "Contact"
url = "/#contact"
weight = -10

# Socal menu items
[[menu.social]]
name = "Facebook"
pre = "<i class='fa fa-lg fa-fw fa-facebook-square'></i>"
url = "https://www.facebook.com/zebbra.ch"
weight = 0

[[menu.social]]
name = "XING"
pre = "<i class='fa fa-lg fa-fw fa-xing-square'></i>"
url = "https://www.xing.com/companies/zebbraag"
weight = 0

[[menu.social]]
name = "LinkedIn"
pre = "<i class='fa fa-lg fa-fw fa-linkedin-square'></i>"
url = "https://www.linkedin.com/company/zebbra/"
weight = 0
